const sub = [
  {
    id: 1,
    type: 'week-track',
    currentWeek: 4,
    seed_name: '',
    seed_image: '',
    baby_growth_image: '',
  },
  {
    id: 2,
    type: 'note',
    mh_book_reminder: [
      {
        id: 1,
        title: 'Are you done with your EP Scan?',
        doc_profile: AppImages.doc_profile,
        doc_name: 'Dr.Nazameen Homaifar',
        doc_exp: '10+ years',
        doc_dept: 'Psychologist',
        color: '#B7CCF0',
        type: 'scan',
      },
      {
        id: 2,
        title: 'Book a Nutrition Counselling session',
        insights: 'Insights 2',
        doc_profile: AppImages.doc_profile,
        doc_name: 'Dr.Nazameen Homaifar',
        doc_exp: '10+ years',
        doc_dept: 'Psychologist',
        color: '#F4DD95',
        type: 'session',
      },
    ],
    mh_notes: [
      {
        id: 1,
        reviewed: true,
        doc_name: 'Dr. Nazaneen Homaifar',
        title: 'Your baby at 4 weeks',
        first_color: '#CBC8F4',
        second_color: '#BDB9F7',
        image: AppImages.first_note,
        doc_profile: AppImages.doc_profile,
        insights: [
          {
            id: 1,
            type: 'doc-profile',
            docName: 'Dr. Nazaneen Homaifar',
            docImage: AppImages.doc_profile,
            docDepartment: 'Obstetrician and Gynaecologist',
          },
          {
            id: 2,
            headerTitle: 'How big is a baby at 4 weeks?',
            length: '2 mm or 0.08 in',
            length_type: '(Crown to Rump)',
            weight: 'Too Small',
            size: 'A flax seed',
            size_image: AppImages.seed_image,
            type: 'child-details',
          },
          {
            id: 3,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is starting to form lungs',
          },
          {
            id: 4,
            type: 'listed-data',
            headerTitle: 'What are prenatal vitamins',
            listed_data: [
              'You might be aware of classic pregnancy symptoms like nausea and a missed period, but how can you tell if you’re pregnant after what’s considered your 3rd week of pregnancy?',
              'The truth is that you can’t, because technically speaking, at 3 weeks pregnant, your baby doesn’t exist yet.',
            ],
          },
          {
            id: 5,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is benefitting from a placenta',
          },
          {
            id: 6,
            type: 'listed-data',
            headerTitle: 'Prenatal vitamins ingredients list',
            listed_data: [
              'Gestational age and fetal age are actually different things.',
              'Your gestational age is calculated from the first day of your last period.',
              'So when experts talk about being 3 weeks pregnant, they are referring to your gestational age.',
            ],
          },
        ],
      },
      {
        id: 2,
        reviewed: true,
        doc_name: 'Dr. Nazaneen Homaifar',
        first_color: '#F4DD95',
        second_color: '#EED485',
        image: AppImages.second_note,
        doc_profile: AppImages.doc_profile,
        title: 'Your baby at 4 weeks',
        insights: [
          {
            id: 1,
            type: 'doc-profile',
            docName: 'Dr. Nazaneen Homaifar',
            docImage: AppImages.doc_profile,
            docDepartment: 'Obstetrician and Gynaecologist',
          },
          {
            id: 2,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is starting to form lungs',
          },
          {
            id: 3,
            type: 'listed-data',
            headerTitle: 'What are prenatal vitamins',
            listed_data: [
              'You might be aware of classic pregnancy symptoms like nausea and a missed period, but how can you tell if you’re pregnant after what’s considered your 3rd week of pregnancy?',
              'The truth is that you can’t, because technically speaking, at 3 weeks pregnant, your baby doesn’t exist yet.',
            ],
          },
          {
            id: 4,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is benefitting from a placenta',
          },
          {
            id: 5,
            type: 'listed-data',
            headerTitle: 'Prenatal vitamins ingredients list',
            listed_data: [
              'Gestational age and fetal age are actually different things.',
              'Your gestational age is calculated from the first day of your last period.',
              'So when experts talk about being 3 weeks pregnant, they are referring to your gestational age.',
            ],
          },
        ],
      },
      {
        id: 3,
        reviewed: true,
        doc_name: 'Dr. Nazaneen Homaifar',
        first_color: '#F6BDDE',
        second_color: '#F8ABD8',
        image: AppImages.first_note,
        doc_profile: AppImages.doc_profile,
        title: 'Your checklist at 4 weeks',
        insights: [
          {
            id: 1,
            type: 'doc-profile',
            docName: 'Dr. Nazaneen Homaifar',
            docImage: AppImages.doc_profile,
            docDepartment: 'Obstetrician and Gynaecologist',
          },
          {
            id: 2,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is starting to form lungs',
          },
          {
            id: 3,
            type: 'listed-data',
            headerTitle: 'What are prenatal vitamins',
            listed_data: [
              'You might be aware of classic pregnancy symptoms like nausea and a missed period, but how can you tell if you’re pregnant after what’s considered your 3rd week of pregnancy?',
              'The truth is that you can’t, because technically speaking, at 3 weeks pregnant, your baby doesn’t exist yet.',
            ],
          },
          {
            id: 4,
            type: 'title',
            image: AppImages.insight_image,
            title: 'This week your baby is benefitting from a placenta',
          },
          {
            id: 5,
            type: 'listed-data',
            headerTitle: 'Prenatal vitamins ingredients list',
            listed_data: [
              'Gestational age and fetal age are actually different things.',
              'Your gestational age is calculated from the first day of your last period.',
              'So when experts talk about being 3 weeks pregnant, they are referring to your gestational age.',
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    type: 'coach',
    mh_coaches: [
      {
        id: 1,
        type: 'water',
        title: 'Drink 8 glasses of water today',
        completed: true,
        gifImage: AppImages.water_coach_image,
        color: '#B7CCF0',
      },
      {
        id: 2,
        type: 'nutrition',
        title: 'Follow the diet plan for today',
        completed: false,
        gifImage: AppImages.water_coach_image,
        color: '#9CC688',
      },
      {
        id: 3,
        type: 'soul',
        title: 'Listen to calming music to promote relaxation',
        completed: false,
        gifImage: AppImages.water_coach_image,
        color: '#F4DD95',
      },
      {
        id: 4,
        type: 'mind',
        title: 'Begin your mind activities for today',
        completed: false,
        gifImage: AppImages.water_coach_image,
        color: '#F6BDDE',
      },
      {
        id: 5,
        type: 'fitness',
        title: 'Complete your fitness regime for the day',
        completed: false,
        gifImage: AppImages.water_coach_image,
        color: '#F4B5AC',
      },
    ],
  },
  {
    id: 4,
    type: 'diet-plan',
    mh_diet_plan: [
      {
        id: 1,
        diet_name: 'Carrot Juice',
        intake_time: 'Early Morning',
        color: '#CBC8F4',
        option: 1,
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
      {
        id: 2,
        diet_name: 'Date 2 Pieces',
        intake_time: 'BreakFast',
        option: 1,
        color: '#F4DD95',
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
      {
        id: 3,
        diet_name: 'Cows Milk',
        option: 2,
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        intake_time: 'Early Morning',
        color: '#F6BDDE',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
      {
        id: 4,
        diet_name: 'Oats with Milk',
        intake_time: 'BreakFast',
        option: 2,
        color: '#9CC688',
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
      {
        id: 5,
        diet_name: 'Apple Juice',
        intake_time: 'Mid Morning',
        option: 1,
        color: '#F4B5AC',
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
      {
        id: 6,
        diet_name: 'Rice and Dal',
        intake_time: 'Mid Morning',
        option: 2,
        color: '#B7CCF0',
        image:
          'https://static.vecteezy.com/system/resources/previews/027/145/762/original/healthy-carrot-smoothie-perfect-for-drink-catalog-ai-generated-png.png',
        contains: ['Carrot', 'Soy', 'Nuts'],
        not_suitable: ['Diabetes', 'Gestational Diabetes Mellius'],
        recipe_link: 'https://www.youtube.com/watch?v=F_7ZoAQ3aJM',
      },
    ],
  },
  {
    id: 5,
    type: 'symptoms',
    mh_log_symptoms: [
      {
        id: 1,
        mood_type: 'Calm Mood',
        title: 'Why it’s good for your baby?',
        image: AppImages.first_log,
        clicked: true,
        docname: 'Dr. Nazaneen Homaifar',
        experience: '10+ years',
        department: 'Gynaecologist',
        color: '#F6BDDE',
      },
      {
        id: 2,
        mood_type: 'Increased Appetite',
        title: 'Why am I so hungry?',
        image: AppImages.first_log,
        clicked: false,
        docname: 'Dr. Nazaneen Homaifar',
        experience: '10+ years',
        department: 'Gynaecologist',
        color: '#F4DD95',
      },
      {
        id: 3,
        mood_type: 'Stress',
        title: 'Stress busting tips that aren’t meditation',
        image: AppImages.first_log,
        clicked: false,
        docname: 'Dr. Nazaneen Homaifar',
        experience: '10+ years',
        department: 'Gynaecologist',
        color: '#CBC8F4',
      },
    ],
  },
  {
    id: 6,
    type: 'medication',
    mh_medications: [
      {
        id: 1,
        tab_type: 'Before Breakfast',
        pills: [
          {
            id: 1,
            medicine_name: "NEUROBION FORT E TABLET 30'S",
            pills: 1,
            taken: false,
            intake_type: 'Before Food',
            intake_time: 'Breakfast',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
          {
            id: 2,
            medicine_name: 'Folic Acid',
            pills: 1,
            taken: false,
            intake_type: 'Before Food',
            intake_time: 'Breakfast',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
          {
            id: 3,
            medicine_name: "NEUROBION FORT E TABLET 30'S",
            pills: 1,
            taken: false,
            intake_type: 'Before Food',
            intake_time: 'Breakfast',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
        ],
      },
      {
        id: 2,
        tab_type: 'After Dinner',
        pills: [
          {
            id: 1,
            medicine_name: "NEUROBION FORT E TABLET 30'S",
            pills: 1,
            taken: false,
            intake_type: 'After Food',
            intake_time: 'Dinner',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
          {
            id: 2,
            medicine_name: 'Folic Acid',
            pills: 1,
            taken: false,
            intake_type: 'After Food',
            intake_time: 'Dinner',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
          {
            id: 3,
            medicine_name: "NEUROBION FORT E TABLET 30'S",
            pills: 1,
            taken: false,
            intake_type: 'After Food',
            intake_time: 'Dinner',
            medicine_type: 'tablet',
            medicine_strength: '50',
            medicine_unit: 'g',
          },
        ],
      },
    ],
  },
  {
    id: 7,
    type: 'trimester',
    mh_trimester_list: [
      {
        id: 1,
        current_trimester: 1,
      },
      {
        id: 2,
        current_trimester: 2,
      },
      {
        id: 3,
        current_trimester: 3,
      },
    ],
    current_trimester: 1,
  },
  {
    id: 8,
    type: 'news',
    mh_news: [
      {
        id: 1,
        title: 'Get the look: Alanna Panday’s best maternity outfits',
        description:
          'Pregnancy is a beautiful journey, and embracing it with style can make you feel even more special. Alanna Panday, a model and social media influencer, has been turning heads with her maternity outfits that blend comfort with high fashion.',
        read_time: 5,
        published_date: '14/07/2024',
        image: AppImages.news_image,
        news_link: '',
      },
      {
        id: 2,
        title:
          'Deepika Padukone Radiates Happiness with Baby Bump in Yoga Photo',
        description:
          'Pregnancy is a beautiful journey, and embracing it with style can make you feel even more special. Alanna Panday, a model and social media influencer, has been turning heads with her maternity outfits that blend comfort with high fashion.',
        read_time: 5,
        published_date: '04/07/2024',
        image: AppImages.news_image,
        news_link: '',
      },
    ],
  },
  {
    id: 9,
    type: 'webinar',
    mh_webinar: [],
  },
];
